projects/config/routes.rb
ProjectManager::Application.routes.draw do

  resources :playagain
  resources :compguessing
  resources :userguessing
  resources :categories
  resources :welcome
  root :to => redirect('/welcome')

end

projects/app/models/bus.rb
require 'starwar'
class Bus
  # all calls to the database must go through the bus
  #we will need to make this a dynamic call -Colton
  #for example
  def self.get_computer_guess_info(category , node_number)
  # case cagetory
  # when "starwars"
  # when "animals"
    case category
      when "starwars"
        if node_number == 1
          @question = Starwar.first
        else
          @question = Starwar.find_by_node_number(node_number)
        end
      #break
    end
  end
  # same with this method
  def self.get_user_guess_info(category , node_number)

  end


end

projects/app/models/starwar.rb
class Starwar <  ActiveRecord::Base

end

projects/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

projects/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    # all calls to the database must go through the bus class
  end
end

projects/app/controllers/compguessing_controller.rb
class CompguessingController < ApplicationController
  def index
    # all calls to the database must go through the bus class
    @question = Bus.get_computer_guess_info("starwars", 3)
  end
end

projects/app/controllers/playagain_controller.rb
class PlayagainController < ApplicationController
  def index
    # all calls to the database must go through the bus class
  end
end

projects/app/controllers/userguessing_controller.rb
class UserguessingController < ApplicationController
  def index
    # all calls to the database must go through the bus class
  end
end

projects/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # all calls to the database must go through the bus class
  end
end

projects/app/helpers/application_helper.rb
module ApplicationHelper
end

projects/app/helpers/projects_helper.rb
module ProjectsHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

projects/app/views/categories/index.html.erb
<html>
<head>
  <h1>This is the Categories page!!!</h1>
</head>

<body>
<p>
  Based off what the user picked on the welcome page, this page will route to the compguessing or userguessing index.
</p>
<p>
  This will after the user has picked a category
</p>

</body>

</html>

projects/app/views/compguessing/index.html.erb
<html>
<head>
  <h1>This is the Computer Guessing page!!!</h1>
</head>

<body>
<div class='box'>
  <%= @question.answer_or_question.to_s%>
</div>
</body>


<%=link_to "Yes", :class => 'button', :id => 'title_header'%>
<%=link_to "No", :class => 'button', :id => 'title_header'%>
</html>

projects/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title 20 Questions
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

projects/app/views/playagain/index.html.erb
<html>
<head>
  <h1>New playagain page.  Will show computer's guess or if user's guess was correct.</h1>
</head>

<body>
<p>
  Computer guesses: ****
</p>
<p>
  You guessed correctly/wrongly!
</p>

<p> Would you like to play again? </p>
<%=link_to "Go to Categories",  {:action=>"index", :controller=>"welcome", :thing=>"some_action"},:class => 'button', :id => 'title_header'%>

</body>

</html>

projects/app/views/userguessing/index.html.erb
<html>
<head>
  <h1>This is the User guessing page!!!</h1>
</head>

<body>
<comment>
  This page is for when the user is guessing what the computer picked
</comment>
</body>

</html>

projects/app/views/welcome/index.html.erb
<html>
<head>
  <h1>This is the Welcome and Pick page!!!</h1>
</head>

<p>
  This link is only here to show you how button_to works
</p>
<p>
  This page will have the welcome message and two buttons
</p>
<p>
  one button that says pick and the other that says guess
</p>
<body>

<%=link_to "Go to Categories",  categories_path(:thing => 'some_action'),:class => 'button', :id => 'title_header'%>

<!----
Test Link. Store here for now if you want.
<%=link_to "Go to Categories",  {:action=>"index", :controller=>"playagain", :thing=>"some_action"},:class => 'button', :id => 'title_header'%>
--->

</body>

</html>